### ISSUE TITLE
Possible bug in hindsight- Failing with error

### ISSUE THREAD

**Issue by mbunde** [obsidianforensics/hindsight#93]
**Describe the problem**
Hindsight is failing with the error **TypeError: can't compare offset-naive and offset-aware datetimes** while trying to parse chrome data on Windows

**Screenshots or Console Output**
If applicable, add screenshots or copy/paste the console output to help explain your problem.

**Expected behavior**

**To Reproduce**

**hindsight.log Snippet**
If possible, attaching the (sanitized if necessary) hindsight.log file output covering the problem run is very helpful for debugging. 

**System Details**
 - Analysis System OS (your forensic workstation): [e.g. Windows 10]
 - Method of Running Hindsight: [e.g. hindsight.py using Python 3.7 on macOS, hindsight_gui.exe on Windows]
 - Hindsight version: [e.g. 20200607]
 - Target System OS: (the OS you pulled the browser files from): [e.g. macOS]
 - Target Browser: [e.g. Chrome]
 - Target Browser Version: [e.g. 83]

**Additional context**
[
![hindsight](https://user-images.githubusercontent.com/20443467/118943723-8e45c900-b95c-11eb-8fb6-129763d5b677.png)
](url)

**Comment by obsidianforensics** [comment]
Hi there, thanks for the report. What version of Hindsight were you running? (it should say a bit higher up in the screenshot)

There was a similar issue in the past that I fixed, so I want to check if this is a new one.

**Comment by obsidianforensics** [comment]
This should be fixed by #103. 

Summary: It adds parsing of Epoch microseconds to to_datetime(); some (synced?) values use this timestamp format. When parsing some of these values as very large epoch second timestamps, it was too large for datetime to convert. A separate bug in the failback parsing caused a timezone-naive timestamp to be created, which led to the sorting issue.

Thanks everyone for reporting this!
